In [2]:
#pip install numpy 
import numpy as np


In [30]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))

<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [5]:
np.zeros([5,7,8,])

array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [8]:
np.ones([4,1,6,])

array([[[1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.]]])

In [9]:
np.eye(4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(-12,1) #Desde el 4 hasta el 20 en un intervalo abierto al final

array([-12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [20]:
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
np.arange(0,20,2.2)

array([ 0. ,  2.2,  4.4,  6.6,  8.8, 11. , 13.2, 15.4, 17.6, 19.8])

In [29]:
arreglo_pares = np.arange(0,20,2)
print(arreglo_pares.size)
print(len(arreglo_pares))
arreglo_tres_dimensiones  = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.size)

10
10
24


In [34]:
#redimensionar el arreglo en funcion del numero de elementos
arreglo_pares.reshape(2,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [49]:
arreglo_pares = np.arange(24)
arreglo_pares.reshape(2,2,2,3)
arreglo_pares.reshape(2,2,3,2)
arreglo_pares.reshape(2,3,2,2)
arreglo_pares.reshape(3,2,2,2)
arreglo_pares.reshape(6,2,2)
arreglo_pares.reshape(2,6,2)
arreglo_pares.reshape(2,2,6)
arreglo_pares.reshape(12,2)
arreglo_pares.reshape(2,12)
arreglo_pares.reshape(4,6)
arreglo_pares.reshape(6,4)
arreglo_pares.reshape(8,3)
arreglo_pares.reshape(3,8)
arreglo_pares.reshape(1,1,1,1,1,1,1,1,24)

array([[[[[[[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
               13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]]]]]]]])

In [52]:
a = np.array([10,10,10])
b = np.array([5,5,5])
#operaciones entre arreglos numpy
#suma
a + b

array([5, 5, 5])

In [53]:
#resta
a - b

array([5, 5, 5])

In [54]:
#division
a / b

array([2., 2., 2.])

In [55]:
#multiplicacion
a * b

array([50, 50, 50])

In [64]:
matrix = np.arange(-30,30,1.5).reshape(4,2,5)
matrix2 = np.arange(-40,20,1.5).reshape(4,2,5)

In [65]:
#suma
matrix + matrix2


array([[[-70., -67., -64., -61., -58.],
        [-55., -52., -49., -46., -43.]],

       [[-40., -37., -34., -31., -28.],
        [-25., -22., -19., -16., -13.]],

       [[-10.,  -7.,  -4.,  -1.,   2.],
        [  5.,   8.,  11.,  14.,  17.]],

       [[ 20.,  23.,  26.,  29.,  32.],
        [ 35.,  38.,  41.,  44.,  47.]]])

In [66]:
#resta
matrix - matrix2

array([[[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]]])

In [67]:
#multiplicacion
matrix * matrix2

array([[[1200.  , 1097.25,  999.  ,  905.25,  816.  ],
        [ 731.25,  651.  ,  575.25,  504.  ,  437.25]],

       [[ 375.  ,  317.25,  264.  ,  215.25,  171.  ],
        [ 131.25,   96.  ,   65.25,   39.  ,   17.25]],

       [[  -0.  ,  -12.75,  -21.  ,  -24.75,  -24.  ],
        [ -18.75,   -9.  ,    5.25,   24.  ,   47.25]],

       [[  75.  ,  107.25,  144.  ,  185.25,  231.  ],
        [ 281.25,  336.  ,  395.25,  459.  ,  527.25]]])

In [68]:
#division
matrix / matrix2

array([[[ 0.75      ,  0.74025974,  0.72972973,  0.71830986,
          0.70588235],
        [ 0.69230769,  0.67741935,  0.66101695,  0.64285714,
          0.62264151]],

       [[ 0.6       ,  0.57446809,  0.54545455,  0.51219512,
          0.47368421],
        [ 0.42857143,  0.375     ,  0.31034483,  0.23076923,
          0.13043478]],

       [[-0.        , -0.17647059, -0.42857143, -0.81818182,
         -1.5       ],
        [-3.        , -9.        , 21.        ,  6.        ,
          3.85714286]],

       [[ 3.        ,  2.53846154,  2.25      ,  2.05263158,
          1.90909091],
        [ 1.8       ,  1.71428571,  1.64516129,  1.58823529,
          1.54054054]]])

In [69]:
a % b


array([0, 0, 0], dtype=int32)

In [70]:
matrix % matrix2

array([[[-30. , -28.5, -27. , -25.5, -24. ],
        [-22.5, -21. , -19.5, -18. , -16.5]],

       [[-15. , -13.5, -12. , -10.5,  -9. ],
        [ -7.5,  -6. ,  -4.5,  -3. ,  -1.5]],

       [[ -0. ,  -7. ,  -4. ,  -1. ,  -2. ],
        [ -0. ,  -0. ,   0. ,   0. ,   3. ]],

       [[  0. ,   3.5,   2. ,   0.5,  10. ],
        [ 10. ,  10. ,  10. ,  10. ,  10. ]]])

In [73]:
#Operaciones escalares 
#sumar
print(a + 7)
#multiplicar
print(a * 10)
#restar
print(a - 2)
#dividir
print(a / 2)

[17 17 17]
[100 100 100]
[8 8 8]
[5. 5. 5.]


In [74]:
arreglo_muestra = np.arange(20).reshape(5,2,2)

In [120]:
#operaciones para hacer filtrado
resp = arreglo_muestra > 5
print(resp)
arreglo_muestra[resp]

[[[False False]
  [False False]]

 [[False False]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]

 [[ True  True]
  [ True  True]]]


array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [121]:
#Operaciones multiples ej menores de 6 o mayores de 12 y pares 
arreglo_muestra[((arreglo_muestra < 6) | (arreglo_muestra > 14)) & (arreglo_muestra % 2 == 0) ]


array([ 0,  2,  4, 16, 18])

In [122]:
A = np.arange(4).reshape((2,2))
B = np.arange(4,8).reshape((2,2))


In [123]:
A.dot(B)

array([[ 6,  7],
       [26, 31]])

In [124]:
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [125]:
B.dot(A)

array([[10, 19],
       [14, 27]])

In [127]:
arreglo_doce = np.arange(12)
arreglo_doce

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [128]:
arreglo_doce.min()

0

In [129]:
arreglo_doce.max()

11

In [132]:
arreglo_doce.reshape(3,2,2)


array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [134]:
arreglo_doce.reshape(3,2,2).sum(axis=0)

array([[12, 15],
       [18, 21]])

In [135]:
arreglo_doce.reshape(3,2,2).sum(axis=1)

array([[ 2,  4],
       [10, 12],
       [18, 20]])

In [136]:
arreglo_doce.reshape(3,2,2).sum(axis=2)

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])