In [4]:
#1 
import numpy as np
zero_vector = np.zeros(10)
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#3
import numpy as np
zero_vector = np.zeros(10)
zero_vector[4]=1
zero_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [13]:
#4
reverse_vector = np.arange(1,51)
reverse_vector = reverse_vector[::-1]
reverse_vector

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [16]:
#5
matrix = np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [170]:
#6
arreglo = [1,2,0,0,4,0]
arr= np.array(arreglo)
result = np.where(arr != 0)[0]
result


array([0, 1, 4], dtype=int64)

In [25]:
#7
m_identity = np.eye(3)
m_identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#8
m_random = np.random.rand(3,3,3)
m_random

array([[[0.12812689, 0.92638073, 0.60052718],
        [0.44253772, 0.90771385, 0.2107757 ],
        [0.28732618, 0.94081413, 0.79526643]],

       [[0.89955951, 0.42428747, 0.42215353],
        [0.55193717, 0.61316092, 0.73815907],
        [0.26540054, 0.81772277, 0.91187137]],

       [[0.37715151, 0.62855826, 0.54440986],
        [0.28357001, 0.03086633, 0.83308621],
        [0.21445785, 0.58886717, 0.7739192 ]]])

In [41]:
#9
m_10x10 = np.random.randint(100, size=(10,10))
print(m_10x10)
print("Menor: "+str(m_10x10.min())+" Mayor: "+str(m_10x10.max()))

[[10 85 82 10 23 20 88 17 98 59]
 [18  9  9 27 12 22 85 33 68 50]
 [73  4 35 63 50 34 84 45 83 18]
 [ 9 13 58 64 96 83 62 79 29 11]
 [97  0 50 40 82 13 84 34 53 76]
 [52 30 81 77 10 32 58 93 10 91]
 [45 36 55 17 73 50 74 27 23 81]
 [82 89 39 22 75 62 59 58 92 32]
 [41 95 93 13 22 43 31 21 87 18]
 [31 24 89 28  8 36 70 97 55 41]]
Menor: 0 Mayor: 98


In [172]:
#10
from scipy import misc
mapache = misc.face()
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]

In [48]:
#11
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
import pandas as pd
myseries = pd.Series(mydict)
display(myseries)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [76]:
#12
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
my_dataframe = ser.to_frame()
my_dataframe.index = myarr
my_dataframe[1]=mylist
my_dataframe
# Transformar la serie en dataframe y hacer una columna indice

0  1
0    0  a
1    1  b
2    2  c
3    3  e
4    4  d
5    5  f
6    6  g
7    7  h
8    8  i
9    9  j
10  10  k
11  11  l
12  12  m
13  13  n
14  14  o
15  15  p
16  16  q
17  17  r
18  18  s
19  19  t
20  20  u
21  21  v
22  22  w
23  23  x
24  24  y
25  25  z

In [75]:
#13
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
my_df =pd.concat([ser1, ser2],axis=1)
my_df

0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25

In [96]:
#14
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser3 = set(ser1).intersection(set(ser2))
ser3

{4, 5}

In [90]:
#15
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser3 = (set(ser2) - set(ser1))
ser3

{6, 7, 8}

In [100]:
#16
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
repeat_items = ser.value_counts()
repeat_items

f    5
d    4
c    4
g    4
e    4
a    3
h    3
b    3
dtype: int64

In [181]:
#17 no
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
repeated_items = ser.value_counts().head(2)
for row in ser.rows:
    print(row)
ser

AttributeError: 'Series' object has no attribute 'rows'

In [131]:
#18 no
ser = pd.Series(np.random.randint(1, 10, 35))
ser_df = ser.to_frame()
ser_df


0     4
1     1
2     7
3     2
4     7
5     4
6     1
7     3
8     8
9     9
10    4
11    8
12    3
13    3
14    2
15    7
16    7
17    4
18    4
19    6
20    9
21    1
22    4
23    1
24    1
25    5
26    8
27    6
28    8
29    5
30    1
31    3
32    8
33    3
34    6
dtype: int32

In [139]:
#19
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u
ser[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

In [183]:
#20 
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
#vertical
ser3 = pd.concat([ser1, ser2],axis=1)
display(ser3)
#horizontal
ser3 = pd.concat([ser1, ser2],axis=0)

0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e

In [187]:
#21 no
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
ser3 = pd.concat([frutas, pesos],axis=1)
ser3.groupby([ser3[0],ser3[1]])
ser3
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['zanahoria', 'banana', 'zanahoria', 'zanahoria', 'zanahoria', 'zanahoria', 'banana', 'zanahoria', 'banana', 'banana']


0     1
0  zanahoria   1.0
1     banana   2.0
2  zanahoria   3.0
3  zanahoria   4.0
4  zanahoria   5.0
5  zanahoria   6.0
6     banana   7.0
7  zanahoria   8.0
8     banana   9.0
9     banana  10.0

In [159]:
#22
path = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
#columnas escogidas
columnas = ["crim","chas","rm","age","tax","medv"]
df = pd.read_csv(
        path,
        nrows = 10,usecols=columnas)
display(df)


crim  chas     rm    age  tax  medv
0  0.00632     0  6.575   65.2  296  24.0
1  0.02731     0  6.421   78.9  242  21.6
2  0.02729     0  7.185   61.1  242  34.7
3  0.03237     0  6.998   45.8  222  33.4
4  0.06905     0  7.147   54.2  222  36.2
5  0.02985     0  6.430   58.7  222  28.7
6  0.08829     0  6.012   66.6  311  22.9
7  0.14455     0  6.172   96.1  311  27.1
8  0.21124     0  5.631  100.0  311  16.5
9  0.17004     0  6.004   85.9  311  18.9